### ISSUE TITLE
useDingbats=FALSE causes problems on OSX/X11

### ISSUE THREAD

**Issue by adsteen** [wilkelab/cowplot#1]
Nice package! Looks to be very useful. However, the cowplot implementation of `ggsave` seems to cause two problems with my OSX system.

* In order to get plots to be sized correctly, I need to use `ggsave(.., type="cairo")`. Since the cowplot `ggsave` doesn't allow extra parameters to be passed through, I can't do this.
* I wrote `save_plot2` to pass extra arguments through to `ggsave`, but I still get an error message about `useDingbats`:

`Error in check.options(new, name.opt = ".X11.Options", envir = .X11env) : 
  c("invalid argument name ‘useDingbats’ in 'grDevices::png(..., width = width, height = height, res = dpi, '", "invalid argument name ‘useDingbats’ in '    units = \"in\")'") `

I think the problem is that only the .pdf device recognizes `useDingbats` in X11, attempting to use `save_plot` to create a png, for instance, fails.

I'd be happy to rewrite around this issue; have put in a pull request.

I'm using ggplot2 1.0.0, R 3.0.3

**Comment by clauswilke** [comment]
`ggsave()` and `save_plot()` should now work correctly, and dingbats are switched off for pdf plots by default.
