### ISSUE TITLE
Release for most recent version requiring R >= 3.3

### ISSUE THREAD

**Issue by pcarbo** [wilkelab/cowplot#104]
I see that the latest versions of `cowplot` in the master branch now require `R >= 3.5`. Could you please tag and/or create a release for the most recent working version of cowplot requiring `R >= 3.3`? (I am using cowplot in an introductory workshop, and requiring that all participants install R 3.5 is not feasible.) Thank you!

**Comment by clauswilke** [comment]
What you’re looking for is 0.9-branch (
https://github.com/wilkelab/cowplot/tree/0.9-branch ), also currently on CRAN.

I’ve purposefully delayed releasing 1.0 since it’ll require R 3.5.
