### ISSUE TITLE
Using any `align` option in `plot_grid()` adds unwanted space to the plot margins when plots have axes on the top/right

### ISSUE THREAD

**Issue by dtdoering** [wilkelab/cowplot#105]
I'm currently trying to align some plots using `plot_grid()`, with the axis text displayed on the outside edges of the plot and with minimal spacing between the plots. I want to have both of their axes aligned. However, when I use the `align` options, the plots have unwanted space between them as if the axes are still in their normal positions. 

Here's a reprex:

```{r plots}
p <- ggplot(mtcars, aes(x = mpg, y = cyl)) + geom_point()

p1 <- p +
  scale_x_continuous(position = "top") +
  theme(plot.background = element_rect(fill = "red"),
        panel.background = element_rect(fill = "white"),
        plot.margin = unit(c(0,0,0,0), "lines"))

p2 <- p +
  scale_x_continuous(position = "top") +
  scale_y_continuous(position = "right") +
  theme(plot.background = element_rect(fill = "blue"),
        panel.background = element_rect(fill = "white"),
        plot.margin = unit(c(0,0,0,0), "lines"))

p3 <- p +
  theme(plot.background = element_rect(fill = "orange"),
        panel.background = element_rect(fill = "white"),
        plot.margin = unit(c(0,0,0,0), "lines"))

p4 <- p +
  scale_y_continuous(position = "right") +
  theme(plot.background = element_rect(fill = "green"),
        panel.background = element_rect(fill = "white"),
        plot.margin = unit(c(0,0,0,0), "lines"))
```

This seems to be due to the use of `scale_x_continuous(position = "right")` or `scale_y_continuous(position = "top")` when attempting to align them:

Un-aligned: OK
```{r}
plot_grid(p1, p2, p3, p4, ncol = 2) 
```
![rplot](https://user-images.githubusercontent.com/8560137/44250225-27968e00-a1b9-11e8-9545-54778a626f8f.png)

Align horizontally: space along middle line
```{r}
plot_grid(p1, p2, p3, p4, ncol = 2, align = "h")
```
![rplot01](https://user-images.githubusercontent.com/8560137/44250226-27968e00-a1b9-11e8-89c0-7538a3a44d29.png)

Align vertically: space along center line
```{r}
plot_grid(p1, p2, p3, p4, ncol = 2, align = "v")
```
![rplot02](https://user-images.githubusercontent.com/8560137/44250227-282f2480-a1b9-11e8-9b14-f74b08f4ac40.png)

Align both: space along both
```{r
plot_grid(p1, p2, p3, p4, ncol = 2, align = "vh")
```
![rplot03](https://user-images.githubusercontent.com/8560137/44250228-282f2480-a1b9-11e8-8ba6-039291d39468.png)

Any idea what could be causing this behavior?

**Comment by clauswilke** [comment]
Yes, this is a limitation of the specific alignment algorithm that I use, and it cannot be circumvented within `plot_grid()`. I recommend you try `ggarrange()` from the egg package or plot composition via the patchwork package.
