### ISSUE TITLE
Errors from ggmap() in R : 

### ISSUE THREAD

**Issue by engineeringbigdata** [wilkelab/cowplot#109]
I've used the ggmap package in R a few months back and I went to create a new tutorial using ggmap and ggplot and I'm receiving a vast amount of errors:

Code used:
```
ggmap(bw_map_us, extent = "device") + 
  geom_point(data = us_attacks, 
             aes(x = Longitude, y = Latitude, color = Total, size = Total)) + 
  scale_colour_gradient(low = "blue", high = "red")
```

**Errors received:**

Theme element panel.border missing
Theme element axis.line.x.bottom missing
Theme element axis.ticks.x.bottom missing
Theme element axis.line.x.top missing
Theme element axis.ticks.x.top missing
Theme element axis.line.y.left missing
Theme element axis.ticks.y.left missing
Theme element axis.line.y.right missing
Theme element axis.ticks.y.right missing
Error in width_cm(guide$barwidth %||% theme$legend.key.width) : 
  Unknown input
In addition: Warning messages:
1: `panel.margin` is deprecated. Please use `panel.spacing` property instead 
2: Removed 1 rows containing missing values (geom_point).

**Comment by clauswilke** [comment]
How is this an issue for the cowplot package?

**Comment by engineeringbigdata** [comment]
Sorry, Can you please delete this.
