### ISSUE TITLE
Increasing the space between plots in plot_grid?

### ISSUE THREAD

**Issue by testbird** [wilkelab/cowplot#11]
Is it possible to increase the spacing between the plots in plot_grid?

The spacing I found discussed in the docs all seemed to refer to labels within plots.

**Comment by clauswilke** [comment]
There are two options. One is to increase the margin of the individual plots, by adding something like:
```
ggplot(...) + theme(plot.margin = unit(c(3,3,3,3), "lines"))
```
This allows you to specify in detail on which sides of the plots you want more space.

Second, you can just scale all the plots down proportionally, by using something like:
```
plot_grid(..., scale = 0.9)
```
In both cases, if this results in misplaced labels, then you can adjust the label positions via the `hjust` and `vjust` options of `plot_grid()`.

**Comment by testbird** [comment]
Thank you for your answer, I tested these options. Unfortunately, it looks like I have to go back to manual plot positioning and labeling in the text document for now.

The scaling makes all plots (and fonts!) smaller (and wastes space on the outer sides).

Manually adjusting the inner margins seems like more work then positioning the plots manually in the text document. And if one of the plots looks bad with a sqare size (needs to be wider, with larger aspect ratio), increasing the upper and lower margins seems to have ill side effects.

What somehow irritates me is that the appearance of the R plotting is so different depending on the "available output canvas dimensions" defined, even with pdf and svg vector formats. Changing canvas sizes, margins, or changing aspect ratios influences line thickness, relative font size and font overlapping in the final document.
For example, one grid can end up having plot labes (e.g. A,B) of different size than those in another grid.

Taking the canvas size as a reference seems backwards to me. I would have thought all vectors (incl. fonts and line thickness) would be based on constant length units like meters (or any derived, like mm, points, etc.) and these could then be transformed without distortions to whatever canvas as desired (keeping aspect ratio or not).

**Comment by crsh** [comment]
Just to add another solution for simple cases (should anyone still be interested), you could simply add an empty plot:

~~~{r}
plot_grid(plot_a, NULL, plot_b, nrow = 1, rel_widths = c(1, 0.05, 1), labels = c("A", "", "B"))
~~~

**Comment by ykang0929** [comment]
While scale <1, then would marker plots smaller; however, scale >1 would get bigger plot and maybe overlap the closer ones (please try different parameters and get better value).
