### ISSUE TITLE
Expanding get_* functions

### ISSUE THREAD

**Issue by malcolmbarrett** [wilkelab/cowplot#110]
I find `get_legend()` very useful. Are you interested in expanding these to other grobs? I was thinking to add just a few particularly useful ones and a generalized one, e.g. titles, axis titles, axes, etc, then `get_grob()` or something like that.

For instance, `get_grob()` and `get_title()` might look like

```{r}
get_grob <- function(plot, pattern) {
  grobs <- as_gtable(plot)$grobs
  
  grobIndex <- which(sapply(grobs, function(x) grepl(pattern, x$name)))
  if (length(grobIndex) == 1) {

    matched_grobs <- grobs[[grobIndex]]
  }
  else {
    matched_grobs <- NULL
  }
}

get_title <- function(plot) {
  get_grob(plot, "plot.title")
}
```

I think this probably glosses over some more complicated aspects of going on to draw certain grobs/lists of grobs, but what do you think?

**Comment by clauswilke** [comment]
In principle yes, though I'm not sure I like the name of `get_grob()`. It's very technical, and at the same time it's not at all clear that it is ggplot2 specific. Maybe something like `get_plot_component()` would work.

I think in the general case you need to be prepared to return more than one grob, e.g. if somebody wants all plot panels in a faceted plot.

If you want you can prepare a PR and then we can discuss details.

**Comment by malcolmbarrett** [comment]
Yes, I agree on both. I'll take a crack at a PR soon.
