### ISSUE TITLE
Interfere with`theme(legend.position="bottom")`

### ISSUE THREAD

**Issue by AlexZHENGH** [wilkelab/cowplot#113]
I was trying to make the legend appear at the bottom of a figure, but **cowplot** seems to interfere with `theme()` in **ggplot2** so the legend locates at the bottom-left corner (instead of the bottom-middle.

Here is a minimum example:

```{r}
library(ggplot2)

ToothGrowth$dose <- as.factor(ToothGrowth$dose)
head(ToothGrowth)

p <- ggplot(ToothGrowth, aes(x=dose, y=len, fill=dose)) + 
  geom_boxplot()
p +  theme(legend.position="bottom")
```
![image](https://user-images.githubusercontent.com/7163285/47393103-7bbc7200-d716-11e8-9628-ddd0ccdbc694.png)

```{r}
library(cowplot)
p +  theme(legend.position="bottom")
```
![image](https://user-images.githubusercontent.com/7163285/47393126-8bd45180-d716-11e8-862a-29a0bc0da47d.png)

I am using version 0.9.3 under R (ver. 3.5.0) and macOS Majove (ver. 10.14).

**Comment by clauswilke** [comment]
Just add `legend.justification = "center"` to the theme statement and it will work.
