### ISSUE TITLE
Main Title for Plots

### ISSUE THREAD

**Issue by cmcoffman** [wilkelab/cowplot#12]
I realize cowplot is publication-focused,and this isn't usually something you see in publications,  but it would be useful if there was a "main title" attribute you could set describing what the plots are. This would just be centered text above all the plots

**Comment by clauswilke** [comment]
I have added a vignette [here](https://htmlpreview.github.io/?https://github.com/wilkelab/cowplot/blob/master/inst/doc/plot_annotations.html) that explains how this effect can be achieved with the functions that are currently available.

**Comment by cmcoffman** [comment]
awesome! Thanks so much for making this tool, I use it constantly!

**Comment by mariabnd** [comment]
In case anyone ends up here via a search engine, here's a link to the [plot_grid vignette](https://github.com/wilkelab/cowplot/blob/master/vignettes/plot_grid.Rmd)  as the one above seems to be broken (the section "Joint plot titles" contains the solution)

**Comment by clauswilke** [comment]
The rendered vignette is available here: https://wilkelab.org/cowplot/articles/plot_grid.html
