### ISSUE TITLE
Feature request: changing base font size for theme_cowplot

### ISSUE THREAD

**Issue by sibojan9** [wilkelab/cowplot#121]
The theme_cowplot is my favorite theme for generating publication-quality plots. Is it possible to provide more flexibility by allowing customizing the base font size of that theme? Currently, I cannot find such an argument for theme_cowplot.

Thanks.

**Comment by clauswilke** [comment]
This feature exists and is fully documented. Please read the reference manual, p. 26.
https://cran.r-project.org/web/packages/cowplot/cowplot.pdf

**Comment by sibojan9** [comment]
Thank you for your prompt reply. I tried theme_cowplot (font_size = 14) from the manual, but it doesn't work towards what I intended. It changed the final font size instead of the base size. In this way, all the font sizes (e.g. axis text, axis label and title) become identical.

**Comment by clauswilke** [comment]
I see. Well, you can install the development version with `devtools::install_github("wilkelab/cowplot")`. It has much improved theme control and this definitely works there. I myself have been using the development version for over a year, and it works fine. The only reason it's not released yet is that it requires R 3.5.0, and I wanted to give people time to upgrade before I require it.

**Comment by sibojan9** [comment]
It works. Thanks.

**Comment by sibojan9** [comment]
Personal opinion, I still like the plot title middle positioned by default. I have no idea why ggplot puts it on the left side. Please feel free not to reply since it is a trivial thing.
