### ISSUE TITLE
switch_axis_position error with axis.title.y=element_blank()

### ISSUE THREAD

**Issue by bynaam** [wilkelab/cowplot#13]
# Paste this message in R console to reproduce the error
# An error occurs on switching the y-axis (but not on the x-axis) when removing axis titles

p1 <- ggplot(mtcars, aes(mpg, disp)) + geom_line(colour = "blue")+
  theme(axis.title.x=element_blank(),axis.title.y=element_blank())
ggdraw(switch_axis_position(p1, axis = 'x'))
# No problem

p1 <- ggplot(mtcars, aes(mpg, disp)) + geom_line(colour = "blue")+
  theme(axis.title.x=element_blank(),axis.title.y=element_blank())
ggdraw(switch_axis_position(p1, axis = 'y'))
# This doesn't work, and i get the following error message
# Error in Ops.unit(gyl$x, grid::unit(0.5, "npc")) : both operands must be units
# The same error occurs on 'xy'. Any ideas?

**Comment by clauswilke** [comment]
This happens because `axis.title.y=element_blank()` completely removes the corresponding column from the internal gtable that ggplot sets up, and `switch_axis_position()` has no way of knowing that.

Here is a simple workaround:
```
p1 <- ggplot(mtcars, aes(mpg, disp)) + geom_line(colour = "blue") + 
    ylab("") +
    theme(axis.title.x=element_blank(), axis.title.y=element_text(size=0))
ggdraw(switch_axis_position(p1, axis = 'y'))
```

I'm not sure off the top of my head how to fix this properly. It's tricky.

**Comment by bynaam** [comment]
That solved the problem. Thanks a lot!

**Comment by kendonB** [comment]
I have basically the same problem but I'd like to retain the ``axis.title`` and omit the ``axis.text`` and ``axis.ticks``. I have a messy workaround by turning them both to white. Changing size to 0 doesn't seem to work.

**Comment by leluna** [comment]
For problems with axis.text: change the labels of the scale to " "  ( which mean additional messy code... ) and use `axis.text.y = element_text(size=0)`. This worked for me, no color change required.  
Haven't found any way for ´axis.ticks´ other than set the color to white either...

**Comment by clauswilke** [comment]
Closing this issue. `switch_axis_position()` has been removed from cowplot due to new upstream functionality in ggplot2.
