### ISSUE TITLE
geom_col axis do not line up in plot_grid

### ISSUE THREAD

**Issue by SMCJB** [wilkelab/cowplot#135]
------

When using plot_grid with vertical layout, the axis values of a geom_col plot, (and hence the bars themselves) do not align with other charts.

```{r}
require(tidyverse)
#> Loading required package: tidyverse
require(cowplot)
#> Loading required package: cowplot
#> 
#> Attaching package: 'cowplot'
#> The following object is masked from 'package:ggplot2':
#> 
#>     ggsave
set.seed(1)
df <- tibble(x = 1:10, a = runif(10), b = a - 0.5, c = cumsum(b), d = cummax(c), e = c - d)
p1 <- ggplot(df) + geom_line(aes(x = x, y = c))
p2 <- ggplot(df) + geom_col(aes(x = x, y = b))
p3 <- ggplot(df) + geom_area(aes(x = x, y = e))
plot_grid(p1, p2, p3, nrow = 3, align = "v")
```

![190601 cowplot issue](https://user-images.githubusercontent.com/12382667/58748785-1a464980-8443-11e9-9f93-78512c13b75f.png)

**Comment by clauswilke** [comment]
Your x scales have different ranges. Explicitly set the range and expansion of the x scales and the problem will go away.

**Comment by SMCJB** [comment]
Thank You Claus, never though to try that. You are of course correct that defining xlim does align the axis correctly,  but it creates a different problem which I'm sure is ggplot related not cowplot related. In the example I gave adding xlim(1,10) to all three plots means the second geom_col plot doesn't correctly show the first and last bars. To rectify this I need to define xlim(0:11) but now all 3 plots have dead space at each end - but everything is now aligned correctly. Also thank you for your work on cowplot. Very grateful that people like you share this with the public so openly.

![190601 cowplot2](https://user-images.githubusercontent.com/12382667/58754595-68863780-8499-11e9-94f9-e4946a16397e.png)
