### ISSUE TITLE
Figure label moves depending on length of text using `draw_figure_label`

### ISSUE THREAD

**Issue by al-obrien** [wilkelab/cowplot#136]
I noticed that if my labels are of varying length, the position of the text will translate to the right. This makes the alignment of my figure captions differ between my images. I initially found this issue while using [`ggpubr`](
https://github.com/kassambara/ggpubr/issues/185#issue-453279699) but it appears that the function `annotate_figure` calls the `draw_figure_label` from `cowplot`, and is likely the source of what I am experiencing.

For example, adjusting some code from the documentation:

```{r}
library(cowplot)

p1 <- qplot(1:10, 1:10)
p2 <- qplot(1:10, (1:10)^2)
p3 <- qplot(1:10, (1:10)^3)
p4 <- qplot(1:10, (1:10)^4)

# Create a simple grid
p <- plot_grid(p1, p2, p3, p4, align = 'hv')

p + draw_figure_label(label = "Short Label")

p + draw_figure_label(label = "THIS IS A SUPER SUPER DUPER LONG LABEL LOOK AT ME ……")
```
![image](https://user-images.githubusercontent.com/37438544/59072966-263a6d00-8882-11e9-9652-ff47e51defc3.png)

![image](https://user-images.githubusercontent.com/37438544/59072962-220e4f80-8882-11e9-96df-4488d4c6b5ce.png)

**Comment by clauswilke** [comment]
Explanation and solution can be found here:
https://stackoverflow.com/questions/47724511/longer-plot-labels-move-to-the-right-when-arranging-plots-with-plot-grid-from-co
