### ISSUE TITLE
Feature request: adding layers to plot_grid()

### ISSUE THREAD

**Issue by privefl** [wilkelab/cowplot#139]
I'm using e.g.
```
library(ggplot2)
cowplot::plot_grid(
  qplot(Sepal.Length, Sepal.Width, data = iris),
  qplot(Petal.Length, Petal.Width, data = iris)
)
```
and see that the resulting object is a ggplot object.

So, I would like to do something like
```
cowplot::plot_grid(
  qplot(Sepal.Length, Sepal.Width, data = iris),
  qplot(Petal.Length, Petal.Width, data = iris)
) + xlim(5, NA)
```
that would be equivalent to
```
cowplot::plot_grid(
  qplot(Sepal.Length, Sepal.Width, data = iris) + xlim(5, NA),
  qplot(Petal.Length, Petal.Width, data = iris) + xlim(5, NA)
)
```

Do you think it would be feasible?

**Comment by clauswilke** [comment]
No, this will never be possible. `plot_grid()` essentially takes a snapshot of a plot and turns it into an image. At this point, no further modifications are possible.

What you're requesting may be in scope for [patchwork.](https://github.com/thomasp85/patchwork)
