### ISSUE TITLE
Align Y axis

### ISSUE THREAD

**Issue by zx8754** [wilkelab/cowplot#14]
Below code illustrates the problem. When 2 plots merged using plot_grid, is it possible to make X axis to align. i.e.: xlims are derived from 2 plots.

```R
library(ggplot2)
library(cowplot)

df1 <- iris
df2 <- iris

df2 <- df2[df2$Sepal.Length <6, ]
df2$Sepal.Width <- df2$Sepal.Width*10000

#ggplot
gg1 <- ggplot(df1, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + geom_line()
gg2 <- ggplot(df2, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + geom_line()

#merge
plot_grid(gg1, gg2, labels = c("A", "B"), align = "v",ncol = 1)
```
![rplot](https://cloud.githubusercontent.com/assets/5212915/9794848/62e79f60-57e5-11e5-9e64-230cfee1ab45.jpeg)

**Comment by clauswilke** [comment]
You need to align vertically, not horizontally.
```
plot_grid(gg1, gg2, labels = c("A", "B"), align = "v",ncol = 1)
```

**Comment by zx8754** [comment]
Sorry, yes got it wrong with "v" instead of "h", how about X alignment?

**Comment by clauswilke** [comment]
You'll have to set the same x limits in the two graphs, e.g. using `+ xlim(4, 8)` when you create the plots. This is not a cowplot issue.

**Comment by zx8754** [comment]
Yes, `xlim` would work, yes it is not an issue, could it be a feature - `align_x = TRUE` ? ;)

**Comment by clauswilke** [comment]
Sorry, this wouldn't make sense. `plot_grid()` knows nothing about axes and shouldn't know about axes. In general, there is no guarantee that two axes can even be aligned, one could be discrete and one continuous. Putting the logic required for what you want into `plot_grid()` would basically replicate the whole `scale_x_...` and `scale_y_...` mechanisms from ggplot2. It's much easier and more sensible to just set the axes appropriately in the individual plots.
