### ISSUE TITLE
Side effect from merely loading the package

### ISSUE THREAD

**Issue by daattali** [wilkelab/cowplot#15]
I've noticed that by simply loading the package, the ggplot2 theme is changed

https://github.com/wilkelab/cowplot/blob/master/R/setup.R#L5-L8

I feel like this is not a good practice, and it's a bit annoying and unpredictable.  Would be nice if there was an explicit way to revert back, and even better if attaching the package would not have this side effect.

**Comment by clauswilke** [comment]
The main purpose of cowplot is to make it as simple as possible for students in my lab to make figures I find acceptable. Changing the theme is an important (maybe the most important) part of that.

If you want to use the default ggplot2 theme, just add `theme_set(theme_gray())` to your code after loading cowplot.

**Comment by daattali** [comment]
Thank you for responding promptly

**Comment by daattali** [comment]
This has now been fixed :)
