### ISSUE TITLE
Legend right-padding in plot_grid with rel_widths on Ubuntu but not on MacOS

### ISSUE THREAD

**Issue by adamaltmejd** [wilkelab/cowplot#155]
Having a problem that I'm not really able to produce a reprex for. When building the plots for this site (http://adamaltmejd.se/covid/ repo: https://github.com/adamaltmejd/covid) locally on MacOS, it looks like it should. But the Github action running on ubuntu latest seems to use the legend widths from `rel_widths = c(1,1)` also when `rel_widths = c(1, 1.5)`. See attached screenshots. 

![Screenshot 2020-05-04 at 14 26 29](https://user-images.githubusercontent.com/736668/80965700-4d434b00-8e13-11ea-968c-4489e197e19b.png)
![Screenshot 2020-05-04 at 14 22 11](https://user-images.githubusercontent.com/736668/80965708-5207ff00-8e13-11ea-97be-88be6172175e.png)

**Comment by adamaltmejd** [comment]
Just realized it is actually not due to rel_widths. Here is the plot built on Github with `rel_widths = c(1,1)`
![asd](https://user-images.githubusercontent.com/736668/80967319-6e596b00-8e16-11ea-8e40-125ad9f21904.png)

**Comment by clauswilke** [comment]
Looks like you're using a non-standard font. Try a different null device and see if that works:
https://wilkelab.org/cowplot/reference/set_null_device.html

If this helps, you can also consider implementing a null device using [ragg,](https://cran.r-project.org/web/packages/ragg/index.html) as it should have better cross-platform performance. (I should probably make that the default anyways.)

You can see the code here to implement a null device:
https://github.com/wilkelab/cowplot/blob/06aeeb449ccc0fb343eb03c83111df7b171e73af/R/set_null_device.R#L62-L69

**Comment by adamaltmejd** [comment]
I was using `cowplot::set_null_device("pdf")` because `cowplot::set_null_device(cairo_null_device(width = 11.46, height = 6))` did not work. Throws error `images cannot be created with other units than 'px' if dpi is not specified`. But maybe I could try with a custom version setting dpi as well.

**Comment by clauswilke** [comment]
I may have to improve the documentation. The Cairo null device is meant to be used like this: 
``` r
set_null_device(cairo_null_device)
```

**Comment by adamaltmejd** [comment]
Tried that too. Same error. It seems to lack a setting for resolution.

**Comment by clauswilke** [comment]
Ah, Ok, thanks for letting me know. I'll have to fix this. I never use the Cairo device.
