### ISSUE TITLE
crash/error in case of printing saved plot_grid() object across R release/devel

### ISSUE THREAD

**Issue by singmann** [wilkelab/cowplot#166]
It seems that `cowplot::plot_grid()` objects created and saved in current R `4.0.2` lead to an error when trying to open them in R devel. The error message is:
```
Error in grid.Call.graphics(C_setviewport, vp, TRUE) : 
  attempt to set index 26/22 in SET_VECTOR_ELT
```

One can see exactly this error message on Github actions checks using R devel on MacOS with my `afex` package: https://github.com/singmann/afex/runs/1017929374?check_suite_focus=true
The vignette also load in such saved objects and consequently fail.

Conversely, if a `cowplot::plot_grid()` object is created and saved in R devel and opens in current/release, it occasionally crashes R (or RStudio). However, this problem depends a bit on the setup. It quite regularly happens in RStudio (on windows) but not in just R. And my Github actions checking the package also fail completely on all OS if it uses binaries created in R-devel.

As a reproducible example, the following is enough:

```r
library(ggplot2)
library(cowplot)

p1 <- ggplot(mtcars, aes(disp, mpg)) + 
  geom_point()
p2 <- ggplot(mtcars, aes(qsec, mpg)) +
  geom_point()

p3 <- plot_grid(p1, p2, labels = c('A', 'B'), label_size = 12)
save(p1, p2, p3, file = "cowplot_current.rda")
save(p1, p2, p3, file = "cowplot_devel.rda")

load("cowplot_current.rda")
load("cowplot_devel.rda")
p3
```
The following zip contains both files from my (windows) system, where `current` was saved in R 4.0.2 and `devel` in R-devel.
[cowplot_issue.zip](https://github.com/wilkelab/cowplot/files/5114008/cowplot_issue.zip)

**Comment by singmann** [comment]
I understand. I just found it weird that it did not happen for `ggplot` plots, but as soon as they are combined by `cowplot::plot_grid`. Anyway, I found a solution for my package. Thanks for the response.

**Comment by dpc10ster** [comment]
I am having the same problem. What is your solution? It would be most helpful. Thanks.
