### ISSUE TITLE
R CMD check with dev ggplot2

### ISSUE THREAD

**Issue by hadley** [wilkelab/cowplot#17]
I see:

```
checking examples ... ERROR
Running examples in ‘cowplot-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: add_sub
> ### Title: Add annotation underneath a plot
> ### Aliases: add_sub
> 
> ### ** Examples
> 
> p1 <- ggplot(mtcars, aes(mpg, disp)) + geom_line(colour = "blue") + background_grid(minor='none')
> ggdraw(add_sub(p1, "This is an annotation.\nAnnotations can span multiple lines."))
Warning: `axis.ticks.margin` is deprecated. Please set `margin` property  of `axis.text` instead
Error in FUN(X[[i]], ...) : 
  Theme element 'text' has NULL property: margin, debug
Calls: ggdraw ... element_render -> calc_element -> lapply -> FUN -> lapply -> FUN
Execution halted
```

Can you please look into ASAP? I'm submitting to CRAN on Friday

**Comment by clauswilke** [comment]
Thanks for pointing this out. I should be able to fix this by your next target release date.

**Comment by clauswilke** [comment]
The cowplot version on github now works with both the current ggplot2 version and the development version. However, I'm not sure I can submit this to CRAN before the new ggplot2 is released, because `R CMD check` complains about unused arguments (in the code paths used for the development version of ggplot2) when the current stable version of ggplot2 is installed.

**Comment by mas29** [comment]
I'm getting the "Theme element 'text' has NULL property: margin, debug" error as well, but only when I run my script in RStudio, rather than the terminal.

**Comment by clauswilke** [comment]
try `R CMD check --as-cran` in the terminal.

**Comment by sdk2116** [comment]
When would you guess this bug will be fixed?

**Comment by clauswilke** [comment]
Bug is fixed on github (see my comment from 28 days ago). I will submit this to CRAN only *after* the next release of ggplot2.

**Comment by sdk2116** [comment]
I am new to using RStudio. Is there any way for me to tell RStudio to use
the GitHub version instead of the Cran version?

**Comment by clauswilke** [comment]
Oh, now I see, the latest version of ggplot2 was just released on CRAN. I'll update cowplot on CRAN as soon as possible.

In the meantime, install the development version, as described [here.](https://github.com/wilkelab/cowplot/blob/master/README.md) Basically, it's this line of code in R:
```
devtools::install_github("wilkelab/cowplot")
```

**Comment by clauswilke** [comment]
cowplot 0.6 is now on CRAN, depends on ggplot2 2.0. This closes this issue.

**Comment by hadley** [comment]
Thanks for all your hard work :smile:
