### ISSUE TITLE
Label positioning is inconsistent

### ISSUE THREAD

**Issue by biol75** [wilkelab/cowplot#175]
![Screenshot 2021-09-06 at 13 26 50](https://user-images.githubusercontent.com/6603866/132217436-8b95eae3-4291-41b1-8bdd-83389d29682b.png)

Brief description of the problem or desired feature.

```{r}
plot_grid(pC1, pC1, pC1, pC1,  nrow=1, labels=c("Label1", "Longer Label2", "C", "D"), label_x = 0 )
```

MacOS 10.15.7, R 4.0.3, cowplot_1.0.0
The first, third and fourth short labels look fine, the long label is offset to the right

Chris

**Comment by clauswilke** [comment]
https://stackoverflow.com/a/47724512/4975218
