### ISSUE TITLE
Default subplot label in plot_grid()

### ISSUE THREAD

**Issue by ustervbo** [wilkelab/cowplot#18]
The plot_grid() is a great way of making plots ready for publication. However, I think it would make sense if the subplots are labelled with upper-case letters by default.

The option `labels = NULL` in plot_grid() could be changed `labels =  "auto"` and by adding 

```
if("auto" %in% labels){
  labels <- LETTERS[1:num_plots]
}
```

to the body of the function, the subplot labels will be generated automatically.

The `num_plots` is already used in the function.

**Comment by clauswilke** [comment]
I use `plot_grid()` in many scenarios in which the auto labeling would get in the way. However, the `if` statement you propose could be added without changing the default `labels` option. I'll ponder some more.

**Comment by clauswilke** [comment]
The `plot_grid()` version on github can now auto-generate labels, either upper-case (keyword `AUTO`) or lower-case (keyword `auto`). See documentation [here.](https://htmlpreview.github.io/?https://github.com/wilkelab/cowplot/blob/master/inst/doc/plot_grid.html

I hope this will be on CRAN within a few days, will submit as soon as ggplot2 2.0 is officially on CRAN (should be tomorrow).
