### ISSUE TITLE
Add common title for the grouped plot and place each label inside individual plots?

### ISSUE THREAD

**Issue by madtraveller** [wilkelab/cowplot#22]
I'm wondering if it's possible to add a common main title for grouped plot? Also is there an option to place each label (e.g. "A", "B") inside individual plots

Thanks!

**Comment by clauswilke** [comment]
Common main title: see [this vignette.](https://cran.r-project.org/web/packages/cowplot/vignettes/plot_annotations.html)

Labels inside plots: adjust `hjust` and `vjust` in `plot_grid()` until the desired effect is achieved.

**Comment by madtraveller** [comment]
Thanks claus!
