### ISSUE TITLE
finer control of alignment

### ISSUE THREAD

**Issue by smsaladi** [wilkelab/cowplot#23]
Thanks for cowplot. It's really been a game changer for making publication quality plots in R.

Would it be possible to implement finer control for subplot alignment in plot_grid? For example, I have a grid like the following

XXXXXXXX     XX
XXXXXXXX     XX
XXXXXXXX     XX

I would like to separately horizontally align the plots in the left column, horizontally align the plots in the left column, and vertically align the plots in each row.

When I use `align = 'hv'`, the end result is that everything has both the same height and width, which is not what I'd like.

Thanks.

**Comment by clauswilke** [comment]
You may have to post specific code for me to understand what you'd like to achieve. I suspect you can achieve the desired effect by using the `rel_widths` option in `plot_grid()`.

**Comment by smsaladi** [comment]
Ok thanks. I just ran into the section on modifying plots as gtable objects, which I think will work. I will try both to come up with an example of what I am trying to achieve.

**Comment by smsaladi** [comment]
I think the issue as that some plots were being created with `theme(aspect.ratio = XX)`. As a result, setting `align` was making things not turn out correctly. Thanks for your help!

**Comment by clauswilke** [comment]
I'm closing this, since there doesn't seem to be an actionable issue remaining. If there is, please open a new issue, preferably with example code explaining the problem.
