### ISSUE TITLE
Unexpected blank page in pdf

### ISSUE THREAD

**Issue by ustervbo** [wilkelab/cowplot#24]
When I run the following I get an unexpected blank page when I save to pdf. Include the `theme(legend.position = "none")` or save via `ggsave()` everything is fine.

```
library(cowplot)

plot.df <- data.frame(value = rnorm(10), variable = c("A", "B"))

p <- ggplot(plot.df, aes(x = variable, y = value, fill = variable))
p <- p + geom_boxplot()

pdf(file = "with_legend.pdf")
plot_grid(p)
dev.off()

pdf(file = "without_legend.pdf")
plot_grid(p + theme(legend.position = "none"))
dev.off()

p
ggsave(filename = "by_gsave.pdf")
```

My `sessionInfo()`

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8   
 [6] LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cowplot_0.6.0 ggplot2_2.0.0

loaded via a namespace (and not attached):
 [1] labeling_0.3     colorspace_1.2-6 scales_0.3.0     plyr_1.8.3       tools_3.2.3      gtable_0.1.2     Rcpp_0.12.3      grid_3.2.3      
 [9] digest_0.6.9     munsell_0.4.3
```

**Comment by clauswilke** [comment]
Yes, this happens. I'm not sure why. However, fundamentally `pdf()` is not the supported mechanism to save ggplot2 figures. The supported mechanism is `ggsave()`. (I'm pretty certain that ultimately, this is a ggplot2 bug, not a cowplot bug.)

**Comment by jscamac** [comment]
I don't think this a ggplot bug.

Problematic cowplot example giving a blank page:
`
library(couplet)
library(ggplot2)
p <- ggplot(mpg, aes(displ, hwy)) +
geom_point() +
facet_wrap(~class)
pdf('test.pdf',width=6.69, height=6.69)
plot_grid(p, p, labels=letters[1:2], ncol = 1, label_size = 11, hjust = -1.5)
dev.off()
`

However, if I replace plot_grid with grid.arrange I don't have the problem,

`
library(gridExtra)
p <- ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  facet_wrap(~class)
pdf('test.pdf',width=6.69, height=6.69)
grid.arrange(p, p, ncol = 1)
dev.off()
`

**Comment by clauswilke** [comment]
It is a ggplot2 bug.

This code produces one page of output:
```
library(ggplot2) # load only ggplot2, not cowplot
p <- ggplot(mpg, aes(displ, hwy)) +
geom_point() +
facet_wrap(~class)
pdf('test.pdf',width=6.69, height=6.69)
p
dev.off()
```

But this produces two:
```
pdf('test.pdf',width=6.69, height=6.69)
g <- ggplot2::ggplotGrob(p)
p
dev.off()
```
So calling the function `ggplot2::ggplotGrob` has the side-effect of creating an extra page in the pdf device, even if the result of that call is assigned to a new object. Cowplot calls `ggplot2::ggplotGrob` to create the grobs it works with.

**Comment by JSanzR** [comment]
Doing: 
pdf("test.pdf", onefile=FALSE)
seems to get rid of the blank page. See: http://stackoverflow.com/questions/12481267/in-r-how-to-prevent-blank-page-in-pdf-when-using-gridbase-to-embed-subplot-insi)

**Comment by marcus1487** [comment]
I have been struggling with this issue myself within my own hacky version of cowplot for while and have not been satisfied with work arounds I have found. I have usually used the `pdf(NULL)` solution when calling ggplotGrob in my own scripts. From what I can tell in discussions about this issue within ggplot2 forums it has to do with the definition of `line` and other plotting values do not have a meaning until a device is opened, so the default device is opened when ggplotGrob is called. I therefore have two comments on this matter.

First, I think that the current correct workaround to use cowplot should be the following:
```
p <- ggplot(mpg, aes(displ, hwy)) + geom_point() + facet_wrap(~class)
p <- ggplotGrob(p)
ggsave(p, 'test.pdf')
## or
pdf('test.pdf')
p
dev.off()
```
Also this is not a `pdf` versus `ggsave` issue as both of the following produce 2 plots.
```
p <- ggplot(mpg, aes(displ, hwy)) + geom_point() + facet_wrap(~class)
ggsave('test.pdf', p)
## and 
pdf('test.pdf')
p
dev.off()
```
Instead it is an issue with any device that can save multiple plots to a single file (e.g. PDF).

Second, even though ggplot needs an open device when a call to `ggplotGrob` is made, I don't believe anything within cowplot depends on the device opened when `ggplotGrob` is called. Thus I believe this bug (whether it is in gggplot2 or not) could be resolved in cowplot by wrapping the only `ggplotGrob` call in cowplot with a null device call. This may be bad form to open a NULL device, but seems like the only solutions as @hadley indicates that there is no plan to fix this issue as noted in hadley/ggplot2#809 . I have opened a fork to resolve this issue (https://github.com/marcus1487/cowplot/tree/blankpage) and am happy to open a pull request for this issue unless this will not be integrated as it is seen as bad form to use a NULL device.

**Comment by clauswilke** [comment]
Yes, please set up a pull request. Two requests from  my side:

1. Comment the code, so it is clear why these lines are added.

2. Verify that this is the only place where we call `ggplot2::ggplotGrob()`.

Thanks!

**Comment by marcus1487** [comment]
I have opened the pull request (with comment). The only ggplotGrob call in the R directory scripts is wrapped in a NULL device call within the draw.R script in the pull request. There are many ggplotGrob calls in the vignettes and docs, but I don't think these need to be fixed with this pull request.

P.S. Thanks for saving me from porting all of my hacky code now that cowplot is here! Great work!
