### ISSUE TITLE
Errors loading cowplot

### ISSUE THREAD

**Issue by camold** [wilkelab/cowplot#26]
Trying to load cowplot fails on R 3.2.3.

Both commands
install.packages("cowplot")
and
devtools::install_github("wilkelab/cowplot")
compile fine.

Upon loading with require(cowplot) I get the following error:
Loading required package: cowplot
Error : .onAttach failed in attachNamespace() for 'cowplot', details:
  call: element_text(family = font_family, face = "plain", colour = "black", 
  error: unused arguments (margin = ggplot2::margin(), debug = FALSE)

**Comment by clauswilke** [comment]
cowplot now requires ggplot 2.0. Looks like you have an old version of ggplot.

**Comment by camold** [comment]
Thanks. Updating ggplot made it work.
Sorry for the inconveniences.

**Comment by Morpheu5** [comment]
Hey, I'm on ggplot2 2.1.0 and I get the exact same error.
