### ISSUE TITLE
Workaround ggplot2 2.1.0 and axis lines not shown

### ISSUE THREAD

**Issue by ustervbo** [wilkelab/cowplot#29]
I have just realised that ggplot2 are not plotting axis lines by default (https://github.com/hadley/ggplot2/issues/1565 and https://github.com/hadley/ggplot2/issues/1567). I imagine this is a mistake, and a work around for now is to issue

``theme_set(theme_cowplot() + theme(axis.line.x = element_line(), axis.line.y = element_line()))``

after loading the cowplot library.

The problem seems to be just with ggplot2 2.1.0

**Comment by clauswilke** [comment]
Thanks for the heads up. I've fixed this in github and am preparing a point release to CRAN now.

**Comment by clauswilke** [comment]
It's on CRAN now.
