### ISSUE TITLE
install.packages not working for me

### ISSUE THREAD

**Issue by smach** [wilkelab/cowplot#3]
When I try install.packages("cowplot") on my Mac, I get this response:

   package ‘cowplot’ is available as a source package but not as a binary
   Warning in install.packages :
    package ‘cowplot’ is not available (for R version 3.1.2)

Installing from GitHub works fine.

**Comment by clauswilke** [comment]
I just uploaded the package yesterday, and it hasn't yet propagated to all mirrors. You could try to add `repos="http://cran.r-project.org/"` to circumvent any mirrors. For example, as of today I can't install from my default mirror but I can from the original CRAN:

    > install.packages("cowplot")
    Warning message:
    package ‘cowplot’ is not available (for R version 3.2.0) 
    > install.packages("cowplot", repos="http://cran.r-project.org/")
    also installing the dependencies ‘stringi’, ‘magrittr’, ‘colorspace’, ‘Rcpp’, ‘stringr’, ‘RColorBrewer’,      ‘dichromat’, ‘munsell’, ‘labeling’, ‘plyr’, ‘digest’, ‘gtable’, ‘reshape2’, ‘scales’, ‘proto’, ‘ggplot2’
    ...
