### ISSUE TITLE
Can't remove axis text and ticks when switching axis position

### ISSUE THREAD

**Issue by tungmilan** [wilkelab/cowplot#35]
I had the following error
Error in Ops.unit(grid::unit(1, "npc"), grob$children[[1]]$y) : 
  both operands must be units

Code I used:

mtcars2 <- mtcars[1:15, ]
mtcars2$name <- row.names(mtcars2)
p3 <- ggplot(mtcars2, aes(x = name, y = mpg, fill = name)) + 
  geom_bar(stat = 'identity', position = "identity") + 
  scale_y_reverse() +
  guides(fill = FALSE) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
ggdraw(switch_axis_position(p3, axis = 'x'))

Any idea what went wrong? Thanks!

Tung

**Comment by clauswilke** [comment]
Is this any different from issue #13?

**Comment by tungmilan** [comment]
Thanks @clauswilke! That workaround solved the issue

library(cowplot)
mtcars2 <- mtcars[1:15, ]
mtcars2$name <- row.names(mtcars2)
p3 <- ggplot(mtcars2, aes(x = name, y = mpg, fill = name)) +
  geom_bar(stat = 'identity', position = "identity") +
  scale_y_reverse() +
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(size = 0)) +
  theme(axis.ticks.x = element_line(size = 0))
ggdraw(switch_axis_position(p3, axis = 'x'))
