### ISSUE TITLE
Potential feature request: dual axes

### ISSUE THREAD

**Issue by smsaladi** [wilkelab/cowplot#36]
There has been some discussion of creating plots with dual axes to highlight the equivalance between scales. For example, a plot of temperature vs. time with a left axis in Celcius and the right in Fahrenheit. There have been some ok solutions like the one [here](http://rpubs.com/kohske/dual_axis_in_ggplot2) and others from the SO discussion [here](http://stackoverflow.com/questions/3099219/plot-with-2-y-axes-one-y-axis-on-the-left-and-another-y-axis-on-the-right).

Given the way the backend is set up in `cowplot`, would there be a good way of implementing this as a feature? If so, I'd be happy to try and help out by submitting a PR if you have a suggestion of how to implement it within the existing code.

**Comment by shrektan** [comment]
This is something I'm looking for. +1

**Comment by smsaladi** [comment]
[SO answer](http://stackoverflow.com/a/36761846/2320823) that does this using [`vinvert_title_grob`](https://github.com/wilkelab/cowplot/blob/master/R/switch_axis.R#L20) in the process

**Comment by smsaladi** [comment]
Functionality in ggplot 2
