### ISSUE TITLE
Font for labels for plot_grid

### ISSUE THREAD

**Issue by mcrone** [wilkelab/cowplot#37]
Hi everyone

I've just started to use ggplot2 and cowplot so I might be overlooking something. I've set the font family for cowplot to helvetica, but it seems that the large figure labels for cowplot are still arial. (shown in the attached file, there is a difference between the G of the X axis and the large label for the actual figure) There doesn't seem to be an option to change the font under plot grid.

Relevant code:

```
theme_set(theme_cowplot(font_size=12,font_family = "helvetica")) 
plot_grid(g.fwd, g.rev, labels = c('G', 'B'), ncol=1)
```

![fontcowplot](https://cloud.githubusercontent.com/assets/4923807/15270538/15e39c70-1a1b-11e6-9c54-81d93aef5802.png)

**Comment by clauswilke** [comment]
You are correct, there is not. The workaround is the same as in issue #32. Draw the labels manually with `draw_plot_label()`, which should allow you to set the font family.

**Comment by mcrone** [comment]
Thank you for the very quick reply! Unfortunately the draw_plot_label() function also does not have the fontfamily property so I had to resort to using the draw_label function and then positioning it.

Here is the resulting graph for those interested showing that the "G" is now in the correct font.
![fixed font plot_grid](https://cloud.githubusercontent.com/assets/4923807/15270661/263864bc-1a1f-11e6-8134-bd91cfa410ec.png)

And here is the code that I used:
```
xoff <- 0.025# relative x position of label, within one plot
yoff <- 0.965 # relative y position of label, within one plot

plot_grid(g.fwd, g.rev, ncol=1)+ draw_label(label="G",x=xoff,y=yoff, fontfamily = "helvetica", fontface = "bold") +draw_label(label="B",x=xoff,y=yoff-0.5, fontfamily = "helvetica", fontface = "bold")
```

**Comment by clauswilke** [comment]
I'm reopening the issue. It's still a bug that needs to be fixed.

**Comment by mcrone** [comment]
Fair enough. Even adding the fontfamily property to the draw_plot_label() would make the workaround a little easier.

Thanks again!

**Comment by clauswilke** [comment]
This works now in cowplot devel:

    p1 <- qplot(1:10, 1:10) + labs(title = "Linear plot")
    p2 <- qplot(1:10, (1:10)^2) + labs(title = "Quadratic plot")
    theme_set(theme_cowplot(font_size=12, font_family = "Times") + 
              theme(text = element_text(colour = "blue")))
    plot_grid(p1, p2, labels = "AUTO")

<img width="659" alt="screen shot 2017-07-27 at 9 01 56 pm" src="https://user-images.githubusercontent.com/4210929/28699395-f747e73c-730e-11e7-858c-9c7cbd7f9d28.png">
