### ISSUE TITLE
Suggestion: better facet grid separation

### ISSUE THREAD

**Issue by dmenne** [wilkelab/cowplot#41]
I like the defaults set by the package, plot look much more publication-ready. I have a small change which you could add to a vignette if setting it globally would hurt:

`theme_update(panel.margin = grid::unit(0.05,"lines"))`

Without this, faceted graphs look confusing.

**Comment by clauswilke** [comment]
It's already in the vignette. Search for "panel_border()". However, I may add this to the default, I agree that a border is needed for faceted graphs.

**Comment by dmenne** [comment]
Oops, my fault. Sorry.
