### ISSUE TITLE
error in using 'cowplot' package

### ISSUE THREAD

**Issue by LyalkaO** [wilkelab/cowplot#42]
I have some issues with  'cowplot', I guess, compatability with 'qqplot2'
When I  'cowplot' package uploaded, I constantly get an error for every plot that I try to run: 
```Error in FUN("text"[[1L]], ...) : 
  Theme element 'text' has NULL property: margin, debug```
I have read some recommendations about this issue  to add
`margin =margin(), debug=F`
so I added it as following:
```element_text(size=14, vjust=2, face="bold", margin =margin(), debug=F)```
but it did not help.
This is very weird, because 2 weeks ago everything worked perfectly fine, but yesterday and today whenever I download 'cowplot', I get this errors for all the plots, disregarding of whether I use 'cowplot' function or not.

**Comment by clauswilke** [comment]
It looks like you're using an old version of ggplot2. What is the output of `packageVersion("ggplot2")` on the R command line?

**Comment by LyalkaO** [comment]
it looks like a recent version: 2.1.0

**Comment by clauswilke** [comment]
cowplot definitely works with ggplot2 version 2.1.0. Can you also run `packageVersion("cowplot")`? Maybe you installed an old version somehow.

**Comment by LyalkaO** [comment]
It is: 0.4.0
I believe it does, because  2 weeks ago I managed to run the plots and plot_grid() worked fantastic.
But I cannot figure out, what happened that It does not work anymore (I did not change anything in the coding).

**Comment by clauswilke** [comment]
You definitely have a version mismatch. cowplot version 0.5 or earlier only works with ggplot2 version 1.X, and cowplot version 0.6 or later only works with ggplot2 version 2.X. Maybe you updated your ggplot2. 

https://github.com/wilkelab/cowplot/blob/master/NEWS
