### ISSUE TITLE
Set strip background to white

### ISSUE THREAD

**Issue by grantmcdermott** [wilkelab/cowplot#43]
A (very) minor suggestion to set the strip background colour to white as default. I love the clean overall look of the cowplot theme, but always end up manually changing the grey strip background whenever I am using cowplot with a faceted or gridded plot:

`theme(strip.background = element_rect(fill = "white"))`

Hardly a game changer, but I do think it better suits the general ethos of the theme.

**Comment by clauswilke** [comment]
We'll have to agree to disagree. It was white in an earlier version and I didn't like it and changed it to grey.
