### ISSUE TITLE
plot_grid: avoid squishing due to axis label

### ISSUE THREAD

**Issue by ashenkin** [wilkelab/cowplot#49]
Hi there,

I asked this on stackoverflow (http://stackoverflow.com/questions/39530116/arrange-multiple-ggplots-but-avoid-squishing-due-to-axis-label/39532814), but wasn't able to resolve it, so am coming here.

I've been using cowplot::plot_grid to arrange multiple ggplot figures, which has been working great in general. However, I've now run into a problem where I want to include the x axis labels on just the bottom plot, but it ends up squishing all the plots (with align = "vh") or the lowest plot (with align = "v") in the column.

Is there any way to perhaps extract the x-axis label grob, and add that as a another plot in plot_grid (perhaps similar to https://github.com/wilkelab/cowplot/blob/master/vignettes/shared_legends.Rmd for legends)? Or another approach?

Thanks very much!

```
library(ggplot2)
library(cowplot)

a = data.frame(a = rnorm(100), b = rep(c("laskjdflsakjd", "cknmlokfjoweijojf"), 50))
b = data.frame(a = rnorm(100), b = rep(c("laskjdflsakjd", "cknmlokfjoweijojf"), 50))
c = data.frame(a = rnorm(100), b = rep(c("laskjdflsakjd", "cknmlokfjoweijojf"), 50))

aplot = ggplot(a, aes(x=b, y=a)) + geom_bar(stat = "identity")
bplot = ggplot(b, aes(x=b, y=a)) + geom_bar(stat = "identity")
cplot = ggplot(c, aes(x=b, y=a)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle=90, vjust = 0.5))

plot_grid(aplot + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
        bplot + theme(axis.text.x = element_blank(), axis.title.x = element_blank()),
        cplot, ncol = 1, align = "vh")
```

![j85iu](https://cloud.githubusercontent.com/assets/1608945/19071606/d846eb6e-8a28-11e6-9f79-cf2a602c2a1e.png)

**Comment by clauswilke** [comment]
I'm closing this issue because it's the same as issue #40. Currently, we can either align or set margins manually. We can't do both, and I can't currently think of a simple way to do this. If I come up with one, I'll update issue #40.
