### ISSUE TITLE
Can't install cowplot in RStudio R 3.2.0?

### ISSUE THREAD

**Issue by dad** [wilkelab/cowplot#5]
Attempt to install in RStudio Version 0.99.441 Win 8.1
```
> install.packages("cowplot")
Warning in install.packages :
  package ‘cowplot’ is not available (for R version 3.2.0)
```
May be lag in CRAN.

**Comment by clauswilke** [comment]
Solution is given in [Issue #3](https://github.com/wilkelab/cowplot/issues/3).
