### ISSUE TITLE
Allow adding vanilla R plots to plot_grid

### ISSUE THREAD

**Issue by flying-sheep** [wilkelab/cowplot#52]
some plotting functions use normal plotting instead of grid-based plotting.

it would be useful to be able to pass `recordedPlot` instances or functions that draw on the R device to `plot_grid`.

currently I use this function, which could be added to `cowplot` internally:

```r
gwrap_plot <- function(x) {
    tree <- grid::grid.grabExpr(gridGraphics::grid.echo(x))
    u <- grid::unit(1, 'null')
    gtable::gtable_col(NULL, list(tree), u, u)
}
```

`gridGraphics::grid.echo` accepts either a function like `function() plot(1:10)` or a [`recordedPlot`](https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/recordplot.html) object, and we could do the same.

This would lead to neat code like this:

```r
p1 <- ggplot(...) + ...
p2 <- function() plot(1:10)

plot_grid(p1, p2)
```

an alternative would be to stay explicit, but export above function (with a better name than `gwrap_plot`)

**Comment by clauswilke** [comment]
Yes, this is a good idea. Can you prepare a pull request?

I think the way to go is to stay explicit, i.e., add a function that converts a base R plot into an object that `plot_grid()` can work with.

**Comment by flying-sheep** [comment]
so basically you just want me to add my `gwrap_plot` to the package (maybe rename it) and document it?

what name do you think would be fitting?

**Comment by clauswilke** [comment]
Yes, exactly. And maybe also mention in the `plot_grid` documentation that this exists.

Your name `gwrap_plot` sounds good to me. Alternatively, maybe `plot_to_gtable`?

**Comment by flying-sheep** [comment]
other alternatives: `gtable_from_plot` (analogous to your other `gtable_*` functions) or `plot2gtable`.

what do you prefer?

**Comment by clauswilke** [comment]
There's already `ggplot_to_gtable` in `draw.R`. I think this could go there as well, with a similar name (`plot_to_gtable`). Also, upon reconsideration, if you want to integrate this functionality into `ggplot_to_gtable` (so conversion is done automatically) that's fine by me as well.

**Comment by flying-sheep** [comment]
well, it’s not converting ggplots, so i could either

- leave two separate functions, or
- deprecate `ggplot_to_gtable` and make `plot_to_gtable` handle both ggplots and normal plots

**Comment by clauswilke** [comment]
I'm fine with either option, but have a weak preference for the latter.
