### ISSUE TITLE
cowplot not available issue - R 3.2.3

### ISSUE THREAD

**Issue by JanaJarecki** [wilkelab/cowplot#53]
Hey,

I run into the (much-reported) issue "package ‘cowplot’ is not available (for R version 3.2.3)" when I run install.packages("cowplot", repos="http://cran.r-project.org/") on my Windows 10 machine.
Can you help solve this?

Thanks, best
Jana

**Comment by clairemcwhite** [comment]
Cowplot now needs at least R 3.3.0 (https://cran.r-project.org/web/packages/cowplot/index.html). Try updating to the latest version of R, and it should work.

**Comment by JanaJarecki** [comment]
Thanks!

**Comment by clauswilke** [comment]
Actually, I just ran into the same problem when trying to install cowplot from within R Studio, even though I have R 3.3.2. Something strange is going on, and it seems to be tied to R Studio. The installation worked when I ran R from the command line in a terminal window.

**Comment by LucasPuente** [comment]
Not ideal, but you can also address this issue by installing an older version of `cowplot` that doesn't require R 3.3.0. For example, install `cowplot 0.6.3` with the following code: ``devtools::install_url("https://github.com/wilkelab/cowplot/archive/0.6.3.zip")```

**Comment by oganm** [comment]
Alternatively one can always fork cowplot and change the required version in the description. Will probably work fine as suggested in #21.

**Comment by clauswilke** [comment]
Closing this since it's not a cowplot bug.
