### ISSUE TITLE
Shrink y axis title margins

### ISSUE THREAD

**Issue by ashenkin** [wilkelab/cowplot#55]
Hi there,

Big fan of cowplot - thanks for putting it out there.  Wondering if there's a way to squish the y axis title margins when needed?  In the attached figure, one can see that too much space is being allocated for the titles (sorry, obligated to obfuscate the words themselves, but i think it's good enough to understand the issue).  I've tried setting theme(y.axis.title(margin = margin(0,0,0,0)) when constructing the constitutent plots, but it has no effect on cowplot's output.  Any help would be greatly appreciated!

Thanks,
Alex

![cowplot y axis label margins](https://cloud.githubusercontent.com/assets/1608945/21936105/e56fa4ec-d9a7-11e6-9783-4662a8d5b052.png)

**Comment by clauswilke** [comment]
Please make up a simplified example of the issue and post reproducible code for it. Thanks!

**Comment by ashenkin** [comment]
Thanks for your attention, Claus.

```
library(ggplot2)
library(cowplot)
plots = list()
for (plotnum in 1:30) {
    tempdf = data.frame(xtemp = rnorm(20), ytemp = rnorm(20))
    plots[[plotnum]] = ggplot(tempdf, aes(x=xtemp, y=ytemp)) + geom_point() + ylab(paste("Plot",plotnum)) + theme_bw() + 
        theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.title.y = element_text(size = 6))
}

tempplot = do.call("plot_grid", c(plots, ncol=3, align = "hv"))
ggsave("example.pdf", tempplot, height = 9, width = 6.5, units = "in")
```
[example.pdf](https://github.com/wilkelab/cowplot/files/710806/example.pdf)

**Comment by clauswilke** [comment]
You can eliminate the margins from the y-axis title via:

    axis.title.y = element_text(size = 6, margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"))

This moves the titles as close to the axis-tick labels as possible, see e.g. Plot 20:

[example.pdf](https://github.com/wilkelab/cowplot/files/711903/example.pdf)

Of course there's still a distance in the other plots, since the y-axis titles are all aligned. I think you would want them to be.
