### ISSUE TITLE
Warning when plot via plot_grid whith French Accent

### ISSUE THREAD

**Issue by hedjour** [wilkelab/cowplot#58]
Hello
When I run this code :
ggplot(data.frame(a=1:5, b = 1:5), aes(a,b)) + geom_point() + labs(title = "é")

No problem
But this one make a Warning :
toto<- ggplot(data.frame(a=1:5, b = 1:5), aes(a,b)) + geom_point() + labs(title = "é")
plot_grid(toto)

Why ?
I use this in a knitr file and can not ignore them
Thank you for any help

**Comment by clauswilke** [comment]
Works fine without problems for me.  Whatever the problem is is not a problem in cowplot.

**Comment by hedjour** [comment]
Can the system be responsive ? 
I work on windows with Latin1 encoding and have this warning : 
Warning message:
In grid.Call(L_stringMetric, as.graphicsAnnot(x$label)) :
  taille de police inconnue pour le caractère 0x17

**Comment by YoannMat** [comment]
Hello there!

I got the same problem without cowplot, it comes from ggplot2.
Can't you specify something like "warning=F" in your knitR code?
