### ISSUE TITLE
Unable to change the color of axis.line

### ISSUE THREAD

**Issue by FrankFromGermany** [wilkelab/cowplot#62]
I've just started to use ggplot2 and cowplot so I might be wrong.

For some reason the color of the axis.line element cannot be changed.
I can change the color of other elements, even axis.ticks.

**Comment by clauswilke** [comment]
Please provide a minimal, reproducible example of the problem.

**Comment by clauswilke** [comment]
You need to change `axis.line.x` and `axis.line.y`.

**Comment by FrankFromGermany** [comment]
@clauswilke 
using axis.line.x and axis.line.y does work. I tried the following, which is in line with ggplot, but does not work:

library(cowplot)
p <- ggplot(mpg, aes(hwy, cty, color = factor(cyl))) + 
  geom_point(size = 2.5) +
  theme(axis.line = element_line(color = "red", linetype = "dotted"))
p

**Comment by clauswilke** [comment]
If a theme changes a derived property (e.g. `axis.line.x`) then changing the parent property has no effect. It's a well-known issue in ggplot2 that has caused some confusing effects, e.g. https://github.com/tidyverse/ggplot2/issues/2058.
