### ISSUE TITLE
Add cowplot to http://www.ggplot2-exts.org/

### ISSUE THREAD

**Issue by adrfantini** [wilkelab/cowplot#64]
I suggest that cowplot should be added to the wonderful repository of ggplot extensions:
http://www.ggplot2-exts.org/

**Comment by clauswilke** [comment]
This is out of my hands. Please suggest this to whoever runs ggplot2-exts.

**Comment by adrfantini** [comment]
Nope, it is not ;)
Just scroll down the page, click the `Submit new extension` button, it will bring you to this simple how-to:
https://github.com/ggplot2-exts/gallery#adding-a-ggplot2-extension

**Comment by clauswilke** [comment]
Ah, Ok. Well, feel free to submit cowplot to ggplot2-exts then. It's not high on my priority list to get this done.

**Comment by adrfantini** [comment]
I do think this should be done by the extension developer, not by a random guy. But if you can provide the `jslibs`, `tags`, `author`, `short` and `description` then I can do it. But then, once you have that, it really takes 30 seconds...
