### ISSUE TITLE
panel.margin is deprecated in ggplot 2.2.0

### ISSUE THREAD

**Issue by smsaladi** [wilkelab/cowplot#65]
which is raising warnings. See fixes from ggthemes here: jrnold/ggthemes#73

    `panel.margin` is deprecated. Please use `panel.spacing` property instead

**Comment by clauswilke** [comment]
cowplot 0.7.0 is compatible with ggplot 2.2.0. Please check your installation.
https://github.com/wilkelab/cowplot/releases/tag/0.7.0

**Comment by smsaladi** [comment]
Sorry, totally right. My fault!

**Comment by engineeringbigdata** [comment]
I see that this is fixed? I've used the ggmap package in R a few months back and I went to create a new tutorial using ggmap and ggplot and I'm receiving a vast amount of errors:
Code used:

ggmap(bw_map_us, extent = "device") + 
  geom_point(data = us_attacks, 
             aes(x = Longitude, y = Latitude, color = Total, size = Total)) + 
  scale_colour_gradient(low = "blue", high = "red")

Errors received:
Theme element panel.border missing
Theme element axis.line.x.bottom missing
Theme element axis.ticks.x.bottom missing
Theme element axis.line.x.top missing
Theme element axis.ticks.x.top missing
Theme element axis.line.y.left missing
Theme element axis.ticks.y.left missing
Theme element axis.line.y.right missing
Theme element axis.ticks.y.right missing
Error in width_cm(guide$barwidth %||% theme$legend.key.width) : 
  Unknown input
In addition: Warning messages:
1: `panel.margin` is deprecated. Please use `panel.spacing` property instead 
2: Removed 1 rows containing missing values (geom_point).
