### ISSUE TITLE
Redefining axis.text.x in theme can break cowplot

### ISSUE THREAD

**Issue by devillemereuil** [wilkelab/cowplot#66]
Changing the settings of the axis.text.x component of theming in ggplot2/cowplot can result in a strong breakage of the package (see MWE attached). 

If I understand correctly, I think the problem is that cowplot rely on theme_nothing (hence theme_void) for the grid layout, but somehow the values provided by axis.text.x do not get overwritten (indeed changing axis.text.x for axis.text doesn't seem to result in breakage in the MWE attached).

Ultimately, I think the issue comes from the fact that theme_void doesn't seem to be full-fledged, compared to other themes (including theme_cowplot, which relies on theme_grey which is full-fledged).

I see two possibles fixes:
- Stop relying on theme_void and make theme_nothing rely on a full-fledged theme like theme_grey
- Report "upstream" to ggplot2, asking Hadley Wickham to make theme_void full-fledged

[MWE.txt](https://github.com/wilkelab/cowplot/files/1151431/MWE.txt)

**Comment by clauswilke** [comment]
This appears to be fixed now in ggplot2 [see here.](https://github.com/tidyverse/ggplot2/issues/2079) In the meantime, for a workaround, see issue #60 or #63.

**Comment by devillemereuil** [comment]
Indeed! Thanks.

**Comment by clauswilke** [comment]
This will be permanently addressed in the upcoming cowplot 0.8.0. In the meantime, it's fixed in the development version on github.
