### ISSUE TITLE
Incorporation of base-R plots into `plot_grid()` can lead to cut-off labels or other drawing artifacts.

### ISSUE THREAD

**Issue by clauswilke** [wilkelab/cowplot#69]
See discussion [here](https://github.com/wilkelab/cowplot/pull/68#issuecomment-318772146).

Tagging @flying-sheep who is part of this discussion.

**Comment by clauswilke** [comment]
I've made a branch `draw_grob` to investigate what's going on. Fixing this will likely require re-implementation of the `draw_grob` function, if it is possible to fix at all.

One thing I've learned already is that clipping doesn't work very well in grid, because nested clip areas aren't possible. *And*, `gtable_col()` by default switches off any clipping that may have been set. See [this issue](https://github.com/hadley/gtable/issues/56) I've filed for gtable.

**Comment by clauswilke** [comment]
Merged the branch back into master. `draw_grob` is now reimplemented, which was useful for several reasons. However, the issue of drawing artifacts may not be solvable.

**Comment by clauswilke** [comment]
I have solved the problem. The issue can be avoided through appropriate settings in `par()` before plotting.

```
p1 <- ggplot(mpg, aes(displ, cty, color=factor(cyl))) + geom_point()
dev.new()
par(xpd = NA, # switch off clipping, necessary to always see axis labels
    bg = "transparent", # switch off background to avoid obscuring adjacent plots
    oma = c(2, 2, 0, 0)) # move plot to the right and up
plot(sqrt)
p6 <- recordPlot()
dev.off()
p7 <- function() image(volcano)
p8 <- gtable::gtable_col("circle", list(grid::circleGrob()))

plot_grid(p1, p6, p7, p8, scale = c(1, .9, .9, .9))
```

<img width="644" alt="screen shot 2017-07-29 at 6 27 46 pm" src="https://user-images.githubusercontent.com/4210929/28749396-c7dc9b2c-748b-11e7-966e-daf25782aedb.png">

**Comment by flying-sheep** [comment]
this is amazing, thank you! looks so good.

**Comment by GuangchuangYu** [comment]
I did something similar a years ago, when I try to let base plot users can also generate a hexsticker in R using my [hexSticker](https://github.com/GuangchuangYu/hexSticker/#base-plot) package. 

I just got an idea of making it to be supported by `cowplot` and created the [base2grob](https://github.com/GuangchuangYu/base2grob) without aware of this (thanks @clauswilke for the link).

**Comment by clauswilke** [comment]
Closing this issue. There have been huge improvements on this front, and this now generally works without problems.
```{r}
p1 <- ggplot(mpg, aes(displ, cty, color=factor(cyl))) + geom_point()
p2 <- ~plot(sqrt)
p3 <- function() image(volcano)
p4 <- gtable::gtable_col("circle", list(grid::circleGrob()))

plot_grid(p1, p2, p3, p4)
```
<img width="824" alt="screen shot 2018-05-05 at 5 35 49 pm" src="https://user-images.githubusercontent.com/4210929/39668134-f4012d4a-508a-11e8-94fa-7a94c6a50d13.png">

Also, if the drawing area becomes too small, cowplot notices and displays an error.
<img width="580" alt="screen shot 2018-05-05 at 5 37 26 pm" src="https://user-images.githubusercontent.com/4210929/39668144-111aae88-508b-11e8-9209-9e7e488c578f.png">

**Comment by flying-sheep** [comment]
awesome!
