### ISSUE TITLE
inconsistent horizontal alignment when y-axis precision varies

### ISSUE THREAD

**Issue by davharris** [wilkelab/cowplot#70]
I'm having trouble aligning two of my plots for a publication. The y-axes on the two plots have different precisions, so one of them takes up more horizontal space to print than the other. 

I've included a reproducible example below:

```
library(cowplot)

x = 1:10

plot_grid(
  qplot(x, x * 10), 
  qplot(x, x / 100), 
  nrow = 2, 
  align = "h")
ggsave("test.png")
```
![test](https://user-images.githubusercontent.com/843017/28800549-1f0b15b4-761b-11e7-8e19-e103a264c1d4.png)

I recognize that this might be a tricky edge case, so feel free to close the issue if it's out of scope. If you have a good workaround, I'd love to hear it though.  Thanks!

**Comment by clauswilke** [comment]
You need to align vertically, `align = "v"`.

```
plot_grid(
  qplot(x, x * 10), 
  qplot(x, x / 100), 
  nrow = 2, 
  align = "v")
```

<img width="484" alt="screen shot 2017-07-31 at 5 26 19 pm" src="https://user-images.githubusercontent.com/4210929/28801058-6889a846-7615-11e7-90ec-48637e358fd2.png">
