### ISSUE TITLE
Better error draw_text when x or y exceeds the drawing size?

### ISSUE THREAD

**Issue by tbates** [wilkelab/cowplot#78]
ggdraw() + draw_text("Hello World!", x = 1, y = 2)
> Warning message:
> Removed 1 rows containing missing values (geom_text). 

**Suggested** error message:
> "one more more values in x or y were outside the legal range", <range of drawing surface provided>

**Comment by clauswilke** [comment]
The error message is generated by `geom_text`. Not sure it's worth the effort to catch this error and then rephrase. Also, if you do it for `draw_text` you'd have to do the same for every other of the draw functions. A lot of work, and a lot of added code that doesn't immediately do anything useful.

**Comment by tbates** [comment]
Makes sense. It confused me, as the data aren't missing. But probably a feature request for `ggplot2` as fixing there will help more folk. Cheers, t
