### ISSUE TITLE
Shared Common Legend Between Panels

### ISSUE THREAD

**Issue by tinyheero** [wilkelab/cowplot#8]
Hi,

I was just wondering if you had a method/technique to have a common legend across multiple plots using the cowplot library? This is similar to the idea listed here:

https://github.com/hadley/ggplot2/wiki/Share-a-legend-between-two-ggplot2-graphs

Thanks,

Fong

**Comment by clauswilke** [comment]
Not at this time. I will think about what kind of functions might provide a powerful and easy solution for this problem. For example, what if the legend should be in the middle between two plots, rather than at the bottom?

**Comment by clauswilke** [comment]
I'm not sure it's worth it to add special code for shared legends to cowplot. However, I wrote a brief vignette that shows how to create compound plots with shared legends in a few lines of code: http://htmlpreview.github.io/?https://github.com/wilkelab/cowplot/blob/master/inst/doc/shared_legends.html

**Comment by richierocks** [comment]
A related useful feature that doesn't appear to have been implemented yet is to allow shared x/y axis labels and a shared main title.

**Comment by clauswilke** [comment]
How to create shared plot titles is now explained [here](http://htmlpreview.github.io/?https://github.com/wilkelab/cowplot/blob/master/inst/doc/plot_annotations.html). Shared x and y axis labels could be created with similar tricks, though I don't think they're a particularly good idea.

I don't foresee implementing additional code for shared legends, titles, or axis labels, so I'm closing this issue.

**Comment by marcus1487** [comment]
I have added a `get_legend` function to extract a legend from a plot as of commit ab23372867f6233f4229bfe1eeae54edaf6eb8e7 which should be included in the next CRAN release (0.6.3). This should make shared legends between plots much more convenient while also maintaining the flexibility to arrange plots and legends as appropriate.

**Comment by clauswilke** [comment]
0.6.3 is now on CRAN
