### ISSUE TITLE
Creating plot grids from image files

### ISSUE THREAD

**Issue by dhimmel** [wilkelab/cowplot#84]
I use `cowplot::plot_grid` to arrange my R plots (made with ggplot2) into a single figure that includes labels. However, oftentimes I'll want to combine one image made in R with an existing image saved to disk (i.e. SVG or PNG).

In short, I want a scripted way to make multi-panel plot where individual panels are labeled and the inputs are image files (preferably vector). Many arguments of `cowplot::plot_grid` wouldn't apply, such as `align`, but the general concept of laying out images in a grid seems the same.

Anyways, is it possible to use existing images in a cowplot grid? If not, does anyone have a recommendation over how to combine images into a larger figure that works on SVG inputs?

**Comment by clauswilke** [comment]
Do the examples at the end of [this vignette](https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html) do what you want?

**Comment by dhimmel** [comment]
> Do the examples at the end of [this vignette](https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html) do what you want?

Ah didn't scroll down far enough! I think [`cowplot::draw_image`](https://rdrr.io/github/wilkelab/cowplot/man/draw_image.html) is exactly what I want.

Specifically I want to do something like this example (function provenance added by me):

```R
p <- ggplot2::ggplot(iris, aes(x = Sepal.Length, fill = Species)) +  ggplot2::geom_density(alpha = 0.7)
p2 <- cowplot::ggdraw() + cowplot::draw_image("http://jeroen.github.io/images/tiger.svg", scale = 0.9)
cowplot::plot_grid(p, p2, labels = "AUTO")
```

Will reopen this if I encounter any problems. Thanks for the link!

**Comment by dhimmel** [comment]
Note `cowplot::draw_image` was [added](https://github.com/wilkelab/cowplot/blob/1ddc59cf661f8f9204ebd8836c93d5336c7f4676/NEWS#L19) in v0.9.0.
