### ISSUE TITLE
Extra padding in plot_grid(..., align="hv")

### ISSUE THREAD

**Issue by fbreitwieser** [wilkelab/cowplot#87]
Thanks for this great package!

I'm trying to create a scatter-plot with marginal densities. I'd like to have the density plots at the top and left border of the scatter plot without any space in-between the plots. However, there remains a gap when I use `plot_grid(..., align="hv")`; see plot 3. When I use `plot_grid(..., align="h")` or `plot_grid(..., align="v")`, the aligned plots are bordering each other as desired (plots 1 and 2).  

Plot 1:  `plot_grid(..., align="h")` works - no space between aligned plots at the bottom
![image](https://user-images.githubusercontent.com/516060/35365839-9aaee2c2-0144-11e8-99f7-520f6bce125f.png)

Plot 2:  `plot_grid(..., align="v")` works - no space between aligned plots on the left
![image](https://user-images.githubusercontent.com/516060/35365858-ab5d0f54-0144-11e8-975a-41fc1b962180.png)

Plot3: With `plot_grid(..., align="hv")` there's space between the plots
![image](https://user-images.githubusercontent.com/516060/35365957-0256023e-0145-11e8-816e-7c7825bef184.png)

Code:
```
DF = data.frame(y=rnorm(100),x=c(rnorm(50),rnorm(50)+2), group=rep(c("A","B"),each=50))
g <- ggplot(DF, aes(col=group, fill=group))
scatter_plot <-  g + geom_point(aes(x=x, y=y)) + theme(legend.position="none")  + theme(plot.margin=unit(c(0,0,1,1),"points"))

density_plot_f <- function(g, x) 
  g + geom_density(aes_string(x), alpha=.5) +
  cowplot::theme_nothing()  + labs(x = NULL, y = NULL) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) 

plotlist <- list(density_plot_f(g, "x"), ggplot(), scatter_plot, density_plot_f(g, "y") + coord_flip())

cowplot::plot_grid(plotlist = plotlist, align="h", axis="b", rel_widths=c(3,1), rel_heights = c(1,3))
cowplot::plot_grid(plotlist = plotlist, align="v", axis="b", rel_widths=c(3,1), rel_heights = c(1,3))
cowplot::plot_grid(plotlist = plotlist, align="hv", axis="b", rel_widths=c(2,1), rel_heights = c(1,2))
```

Thanks!
Florian

**Comment by clauswilke** [comment]
Please take a look at the examples for the `axis_canvas()` function.

**Comment by fbreitwieser** [comment]
That looks great, thanks for the lead!

**Comment by Marc-Ruebsam** [comment]
> > Please take a look at the examples for the `axis_canvas()` function.
> 
> This answer neither explains the origin of this behavior, or whether it is intended, nor does it give a generalized solution to the problem, e.g. in case axis labels are desired for the density plots.

```
pDENSITY <-
  ggplot() +
  theme_bw() +
  geom_density( data = mtcars, aes( x = mpg, fill = factor(cyl) ), alpha = 0.6, size=.2 ) +
  theme( axis.title.x = element_blank(), axis.text.x = element_blank(), plot.margin = unit(c(5.5,5.5,1,5.5), "pt") ) +
  guides( fill = "none" )
pMAIN <-
  ggplot() +
  theme_bw() +
  geom_boxplot( data = mtcars, aes( x = mpg, y = factor(paste0(cyl," cylinders")), fill = factor(paste0(cyl," cylinders")) ) ) +
  theme( axis.title.y = element_blank() ) +
  guides( fill = "none" )
pBAR <-
  ggplot() +
  theme_bw() +
  geom_bar( data = mtcars, aes( y = factor(cyl), fill = factor(cyl), linetype = factor(gear) ), color = "black" ) +
  theme( axis.title.y = element_blank(), axis.text.y = element_blank(), plot.margin = unit(c(5.5,5.5,5.5,1), "pt") )
```
```
plot_grid(
  pDENSITY,
  NULL,
  pMAIN,
  pBAR,
  ncol = 2,
  nrow = 2,
  rel_heights = c(1,3),
  rel_widths = c(2,1),
  align = 'hv',
  axis = 'lbrt' )
```
![image](https://user-images.githubusercontent.com/33220093/175300346-87c6283b-ee94-4509-b117-4604549aa764.png)
... has to much padding.
```
ggdraw(
  insert_yaxis_grob(
    insert_xaxis_grob(
      pMAIN,
      pDENSITY,
      grid::unit(.2, "null"),
      position = "top" ),
    pBAR,
    grid::unit(.2, "null"),
    position = "right" ) )
```
![image](https://user-images.githubusercontent.com/33220093/175300975-899e6b88-c5bd-46b5-a0f2-1512fa0a4241.png)
... is missing axes (and legend).

**Comment by clauswilke** [comment]
Honestly, you're probably better off using patchwork for these kinds of arrangements. The following gets pretty close to what you want (I think).

``` r
library(tidyverse)
library(patchwork)

pDENSITY <-
  ggplot() +
  theme_bw() +
  geom_density( data = mtcars, aes( x = mpg, fill = factor(cyl) ), alpha = 0.6, size=.2 ) +
  theme( axis.title.x = element_blank(), axis.text.x = element_blank(), plot.margin = unit(c(5.5,5.5,0,5.5), "pt") ) +
  guides( fill = "none" )
pMAIN <-
  ggplot() +
  theme_bw() +
  geom_boxplot( data = mtcars, aes( x = mpg, y = factor(paste0(cyl," cylinders")), fill = factor(paste0(cyl," cylinders")) ) ) +
  theme( axis.title.y = element_blank() ) +
  guides( fill = "none" )
pBAR <-
  ggplot() +
  theme_bw() +
  geom_bar( data = mtcars, aes( y = factor(cyl), fill = factor(cyl), linetype = factor(gear) ), color = "black" ) +
  theme( axis.title.y = element_blank(), axis.text.y = element_blank(), plot.margin = unit(c(5.5,5.5,5.5,0), "pt") )


pDENSITY + plot_spacer() + pMAIN + pBAR + plot_layout(ncol = 2, heights = c(1, 3), widths = c(2, 1))
```

![](https://i.imgur.com/8OCv4Cn.png)

<sup>Created on 2022-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Marc-Ruebsam** [comment]
Thank you very much for the reply!
I will have a look at patchwork. The solution looks pretty nice. I played around with `egg` now and was also able to get a result:
```
egg::ggarrange(
  plots = list( pDENSITY, ggplot() + theme_void(), pMAIN, pBAR ),
  ncol = 2, nrow = 2, widths = c(2, 1), heights = c(1, 3) )
```
![image](https://user-images.githubusercontent.com/33220093/175333397-7d9d9425-0ae4-49de-bedd-408614565afb.png)
The only difference I can spot is the x-axis label at the density plot (before looking into whether this can be adapted).

**Comment by clauswilke** [comment]
Yes, patchwork will align all the axis labels, and that may not be what you want. It can cause some labels to float in space, as we see in my example.
