### ISSUE TITLE
How to change the labels font from bold to plain 

### ISSUE THREAD

**Issue by ysubash** [wilkelab/cowplot#91]
Hi! Wilke,

I have just started using cowplot for my work and solves the orientation and sub plot labelling issues..I have one small issue, which i could not figure out..

By default the labels are bold and i did not find a way to make the **fontface** to **plain** .. I checked on theme_cowplot, but it does not have the option for  fontface

```
  plot2by2 = plot_grid(plt.G1+theme(legend.position="none"), 
                       plt.G2+theme(legend.position="none"),
                       plt.B1+theme(legend.position="none"),
                       plt.B2+theme(legend.position="none"),labels = c("(a)","(b)","(c)","(d)"),nrow = 2,ncol=2)
```

**Comment by clauswilke** [comment]
Github issues are not for user support. Read the documentation or ask on Stackoverflow.

**Comment by ysubash** [comment]
Hi! Wilke,

Found the problem, i was using the old version 0.7.0 , updated to the latest version..

Thanks

**Comment by Make42** [comment]
@clausilke: Well, it would be nice if it was documented...

`label_fontface (optional) Font face of the plot labels. Default is "bold"`

in https://cran.r-project.org/web/packages/cowplot/cowplot.pdf for plot_grid is hardly sufficient.
