### ISSUE TITLE
Use cowplot theme directly without reloading the package

### ISSUE THREAD

**Issue by sibojan** [wilkelab/cowplot#95]
`ggplot()  + theme_cowplot `doesn't work.
Is there any way like `ggplot() +theme_gray()`  to use cowplot theme directly?
Thank you,

**Comment by clauswilke** [comment]
`ggplot() + cowplot::theme_cowplot()`

In the future, please use the issue system only for bug reports or feature requests. Usage questions can be asked on stackoverflow.com.

**Comment by sibojan** [comment]
Thank you. Will follow your  suggestion.
