### ISSUE TITLE
"color" versus "colour" with `ggplot2` versus `cowplot`

### ISSUE THREAD

**Issue by IndrajeetPatil** [wilkelab/cowplot#96]
Is there a possibility to have `cowplot` behave the same way as `ggplot2` with regards to being indifferent to `color` versus `colour`? 

Given that `cowplot` is designed to combine plots prepared with `ggplot2`, it's always confusing for me to keep track of spelling of color I am using when I mix functions from these two packages.  It will be great if `cowplot` inherits the `ggplot2` behavior in this regard.

**Comment by clauswilke** [comment]
Feel free to submit a pull request.
