### ISSUE TITLE
Feature Request:  Allow Optional No Legend in get_legend

### ISSUE THREAD

**Issue by billdenney** [wilkelab/cowplot#98]
Thank you for the `cowplot` package!

I sometimes have figures that have a mix of legends-- or not.  And, I'd like to be able to simply arrange them with `plot_grid` by pulling out the panels and legends.  Can the `get_legend` have an optional argument added `allow_null_legend` (or similar) so that in the case of no legend present, it would return `NULL` (and perhaps give a warning)?

``` r
library(cowplot)                        
#> Loading required package: ggplot2
#> 
#> Attaching package: 'cowplot'
#> The following object is masked from 'package:ggplot2':
#> 
#>     ggsave
get_legend(                             
ggplot(data.frame(A=1), aes(x=A, y=A)) +
geom_point())                           
#> Error in get_legend(ggplot(data.frame(A = 1), aes(x = A, y = A)) + geom_point()): Plot must contain a legend
```

**Comment by clauswilke** [comment]
Yes, this seems reasonable. Would you be able to provide a pull request, or at least test the development version if I implement it?
